module.exports = function ( karma ) {
  karma.set({

    basePath: '../../',

    files: [
      'vendor/static/modernizr/modernizr.min.js',
      'vendor/static/Base64/Base64.js',
      'vendor/static/bluebird/bluebird.min.js',
      'vendor/bower/lodash/lodash.min.js',
      'vendor/bower/underscore.string/dist/underscore.string.js',
      'vendor/bower/fastclick/lib/fastclick.js',
      'vendor/bower/dropzone/dist/min/dropzone.min.js',
      'vendor/static/iconic/iconic.min.js',
      'vendor/bower/hammerjs/hammer.js',
      'vendor/bower/photoswipe/dist/photoswipe.js',
      'vendor/bower/photoswipe/dist/photoswipe-ui-default.js',
      'vendor/bower/angular/angular.js',
      'vendor/bower/angular-touch/angular-touch.js',
      'vendor/bower/angular-sanitize/angular-sanitize.js',
      'vendor/bower/angular-resource/angular-resource.js',
      'vendor/bower/angular-animate/angular-animate.js',
      'vendor/bower/angular-ui-router/release/angular-ui-router.js',
      'vendor/bower/angular-local-storage/dist/angular-local-storage.js',
      'vendor/bower/angular-translate/angular-translate.js',
      'vendor/bower/angular-gestures/gestures.js',
      'vendor/static/ng-wig/ng-wig.js',
      'vendor/bower/angular-google-maps/dist/angular-google-maps.js',
      'grunt_assets/html2js.temp/app/templates-app.js',
      'grunt_assets/html2js.temp/app/templates-common.js',
      'vendor/bower/angular-mocks/angular-mocks.js',
      'common/constants/constants.js',
      'common/dms-image/dms-image.js',
      'common/iconic/iconic.js',
      'common/jsextension/jsextension.js',
      'common/kit-carousel/kit-carousel.js',
      'common/kit-cookies/kit-cookies.js',
      'common/masonry/masonry.js',
      'common/number-formatter/number-formatter.js',
      'common/page-title/page-title.js',
      'common/route-config-service/route-config.js',
      'common/social-share/social-share.js',
      'common/text-ellipsis/text-ellipsis.js',
      'common/translate-highlight/translate-highlight.js',
      'common/underscore-compact-object/underscore-compact-object.js',
      'common/window-resize-listener/window-resize-listener.js',
      'common/constants/api/api.js',
      'common/dms-image/controllers/dms-image-controller.js',
      'common/dms-image/directives/dms-image-directive.js',
      'common/dms-image/services/dms-image-service.js',
      'common/dms-image/values/dms-dimension-values.js',
      'common/dms-image/values/dms-image-ratios-value.js',
      'common/iconic/directives/iconic-directive.js',
      'common/iconic/services/iconic-service.js',
      'common/kit-cookies/factories/kit-cookies-factory.js',
      'common/masonry/controllers/masonry-controller.js',
      'common/masonry/directives/masonry-brick-directive.js',
      'common/masonry/directives/masonry-directive.js',
      'common/number-formatter/directives/number-formatter-directive.js',
      'common/page-title/factories/page-title-factory.js',
      'common/route-config-service/services/route-config-service.js',
      'common/social-share/controllers/social-share-controller.js',
      'common/social-share/directives/social-share-directive.js',
      'common/social-share/services/social-share-facebook-service.js',
      'common/social-share/services/social-share-google-service.js',
      'common/social-share/services/social-share-pinterest-service.js',
      'common/social-share/services/social-share-twitter-service.js',
      'common/text-ellipsis/directives/text-ellipsis-directive.js',
      'common/translate-highlight/directives/translate-directive.js',
      'common/translate-highlight/directives/translate-highlight-tooltip-directive.js',
      'common/translate-highlight/services/translate-hightlight-service.js',
      'common/window-resize-listener/services/window-resize-listener-service.js',
      'app/advanced-search/advanced-search.js',
      'app/exhibition/exhibition.js',
      'app/feature/feature.js',
      'app/folder/folder.js',
      'app/hidden-translations/hidden-translations.js',
      'app/home/home.js',
      'app/info/info.js',
      'app/mypage/mypage.js',
      'app/object/object.js',
      'app/owner/owner.js',
      'app/search/search.js',
      'app/shopping_cart/shopping_cart.js',
      'app/story/story.js',
      'app/user/user.js',
      'app/version/version.js',
      'app/app.js',
      'app/advanced-search/controllers/advanced-search-controller.js',
      'app/app/constants/media-licenses.js',
      'app/app/controllers/app-controller.js',
      'app/app/controllers/comments-controller.js',
      'app/app/controllers/media-carousel-controller.js',
      'app/app/controllers/modal-simple-controller.js',
      'app/app/controllers/share-link-controller.js',
      'app/app/directives/comments-directive.js',
      'app/app/directives/delete-confirm/controllers/delete-confirm-controller.js',
      'app/app/directives/delete-confirm/delete-confirm-directive.js',
      'app/app/directives/delete-confirm/ng-confirm-directive.js',
      'app/app/directives/delete-confirm/services/delete-confirm-service.js',
      'app/app/directives/dropzone/_constants/dropzone-directive-mime-constant.js',
      'app/app/directives/dropzone/controllers/dropzone-directive-controller.js',
      'app/app/directives/dropzone/dropzone-directive.js',
      'app/app/directives/footer-search-directive.js',
      'app/app/directives/image-onload-directive.js',
      'app/app/directives/lang-selector-directive.js',
      'app/app/directives/media-carousel-container-directive.js',
      'app/app/directives/media-carousel-controls-directive.js',
      'app/app/directives/media-carousel-directive.js',
      'app/app/directives/media-carousel-slide-directive.js',
      'app/app/directives/modal-directives.js',
      'app/app/directives/nav-main-directive.js',
      'app/app/directives/nav-mobile-directive.js',
      'app/app/directives/nav-secondary-directive.js',
      'app/app/directives/ng-enter-directive.js',
      'app/app/directives/share-directive.js',
      'app/app/directives/tooltip-directive.js',
      'app/app/factories/angular-translate-loader.js',
      'app/app/factories/api-cache-factory.js',
      'app/app/factories/google-analytics-factory.js',
      'app/app/factories/upload-cache-factory.js',
      'app/app/filters/app-filters.js',
      'app/app/other/indexof-polyfill.ie8.header.js',
      'app/app/services/api-service.js',
      'app/app/services/license-deed-locale-service.js',
      'app/app/services/modal-service.js',
      'app/app/services/user-service.js',
      'app/app/values/app-data-value.js',
      'app/exhibition/controllers/exhibition-controller.js',
      'app/feature/controllers/feature-controller.js',
      'app/feature/directives/feature-image-focus-directives.js',
      'app/feature/directives/feature-image-movable-directives.js',
      'app/feature/services/feature-service.js',
      'app/folder/controllers/folder-controllers.js',
      'app/hidden-translations/controllers/hidden-translations-controller.js',
      'app/hidden-translations/services/hidden-translations-service.js',
      'app/home/controllers/home-controller.js',
      'app/home/directives/home-overview-stats-directive.js',
      'app/home/directives/home-publised-stats-directive.js',
      'app/info/controllers/info-controller.js',
      'app/info/controllers/info-section-controller.js',
      'app/mypage/controllers/mypageController.js',
      'app/object/controllers/object-controller.js',
      'app/object/directives/object-about-owner/controllers/object-about-owner-controller.js',
      'app/object/directives/object-about-owner/object-about-owner-directive.js',
      'app/object/directives/object-additional-info-list-wrapper/object-additional-info-list-wrapper-directive.js',
      'app/object/directives/object-audio-list/object-audio-list-directive.js',
      'app/object/directives/object-comments/controllers/object-comments-controller.js',
      'app/object/directives/object-comments/object-comments-directive.js',
      'app/object/directives/object-info-list/object-info-list-detail-directive.js',
      'app/object/directives/object-info-list/object-info-list-detail-expand-directive.js',
      'app/object/directives/object-info-list/object-info-list-detail-link-directive.js',
      'app/object/directives/object-info-list/object-info-list-detail-multiline-directive.js',
      'app/object/directives/object-info-list/object-info-list-directive.js',
      'app/object/directives/object-info-translate-directive.js',
      'app/object/directives/object-license/controllers/object-license-controller.js',
      'app/object/directives/object-license/object-license-directive.js',
      'app/object/directives/object-media-license/controllers/object-media-license-controller.js',
      'app/object/directives/object-media-license/object-media-license-directive.js',
      'app/object/directives/object-media-toolbar/controllers/object-media-toolbar-controller.js',
      'app/object/directives/object-media-toolbar/object-media-toolbar-directive.js',
      'app/object/directives/object-related-articles/controllers/object-related-articles-controller.js',
      'app/object/directives/object-related-articles/object-related-articles-directive.js',
      'app/object/directives/object-related-context/controllers/object-related-context-controller.js',
      'app/object/directives/object-related-context/object-related-context-directive.js',
      'app/object/directives/object-related-objects/controllers/object-related-objects-controller.js',
      'app/object/directives/object-related-objects/object-related-objects-directive.js',
      'app/object/directives/object-subjects/controllers/object-subjects-controller.js',
      'app/object/directives/object-subjects/object-subjects-directive.js',
      'app/object/directives/object-tags/controllers/object-tags-controller.js',
      'app/object/directives/object-tags/object-tags-directive.js',
      'app/object/directives/object-wikipedia-snippet/controllers/object-wikipedia-snippet-controller.js',
      'app/object/directives/object-wikipedia-snippet/object-wikipedia-snippet-directive.js',
      'app/object/factories/object-cache-factory.js',
      'app/object/factories/object-related-articles-cache-factory.js',
      'app/object/render-authority-generic/controllers/object-render-authority-generic-controller.js',
      'app/object/render-authority-generic/object-render-authority-generic-directive.js',
      'app/object/render-exhibition/controllers/object-render-exhibition-controller.js',
      'app/object/render-exhibition/object-render-exhibition-directive.js',
      'app/object/render-folder/controllers/object-render-folder-controller.js',
      'app/object/render-folder/object-render-folder-directive.js',
      'app/object/render-generic/object-render-generic-directive.js',
      'app/object/render-story/object-render-story-directive.js',
      'app/object/services/object-info-template-translation-service.js',
      'app/object/services/object-license-data-service.js',
      'app/object/services/object-related-articles-service.js',
      'app/object/services/object-service.js',
      'app/owner/controllers/owner-controllers.js',
      'app/owner/controllers/owner-letter-index-controller.js',
      'app/owner/controllers/owner-menu-controller.js',
      'app/owner/directives/owner-letter-index-directive.js',
      'app/owner/directives/owner-menu-directive.js',
      'app/owner/filters/owner-filter.js',
      'app/owner/services/owner-data-service.js',
      'app/owner/services/owner-list-service.js',
      'app/search/controllers/explore-objects-controller.js',
      'app/search/controllers/search-controller.js',
      'app/search/controllers/search-popular-subjects-controller.js',
      'app/search/directives/explore-objects-directive.js',
      'app/search/directives/search-filters/controllers/search-filters-controller.js',
      'app/search/directives/search-filters/search-filters-directive.js',
      'app/search/directives/search-form-directive.js',
      'app/search/directives/search-input-directive.js',
      'app/search/directives/search-legend/controllers/search-legend-controller.js',
      'app/search/directives/search-legend/search-legend-directive.js',
      'app/search/directives/search-origin-navigator/controllers/search-origin-navigator-controller.js',
      'app/search/directives/search-origin-navigator/search-origin-navigator-directive.js',
      'app/search/directives/search-popular-subjects-directive.js',
      'app/search/directives/search-results-options/controllers/search-results-options-controller.js',
      'app/search/directives/search-results-options/search-results-options-directive.js',
      'app/search/directives/search-results/controllers/search-results-controller.js',
      'app/search/directives/search-results/search-results-directive.js',
      'app/search/directives/search-section/controllers/search-section-controller.js',
      'app/search/directives/search-section/search-section-directive.js',
      'app/search/services/search-factory.js',
      'app/search/services/search-popular-subjects-service.js',
      'app/search/services/search-results-cache-service.js',
      'app/search/services/search-service.js',
      'app/shopping_cart/controllers/order-controller.js',
      'app/shopping_cart/controllers/shopping_cart-controller.js',
      'app/shopping_cart/services/shopping_cart-service.js',
      'app/story/controllers/story-controller.js',
      'app/story/services/story-service.js',
      'app/user/controllers/user-menu-controller.js',
      'app/user/controllers/userController.js',
      'app/user/directives/user-menu-directive.js',
      'app/user/services/favoritesService.js',
      'app/version/controllers/versionController.js',
      'app/advanced-search/_tests/advanced-search.spec.js',
      'app/app/_tests/app.spec.js',
      'app/app/_tests/user-service.spec.js',
      'app/app/directives/delete-confirm/_tests/delete-confirm-service.spec.js',
      'app/exhibition/_tests/exhibition.spec.js',
      'app/feature/_tests/feature-service.spec.js',
      'app/folder/_tests/folder.spec.js',
      'app/hidden-translations/_test/hidden-translations-service.spec.js',
      'app/home/_tests/home.spec.js',
      'app/info/_tests/info.spec.js',
      'app/mypage/_tests/mypage.spec.js',
      'app/object/_tests/object-service.spec.js',
      'app/owner/_tests/owner-data-service.spec.js',
      'app/owner/_tests/owner-list-service.spec.js',
      'app/search/_tests/search-factory.spec.js',
      'app/search/_tests/search-service.spec.js',
      'app/shopping_cart/_tests/shopping_cart-service.spec.js',
      'app/story/_test/story-service.spec.js',
      'app/user/_tests/user.spec.js',
      'app/version/_tests/verison.spec.js',
      
	  'vendor/static/app-data-value.js'
    ],
    frameworks: [ 'jasmine' ],
    plugins: [ 'karma-jasmine', 'karma-firefox-launcher', 'karma-chrome-launcher', 'karma-phantomjs-launcher', 'karma-coverage' ],
    reporters: ['progress', 'coverage', 'dots'],

//	    reporters: ['dots'],
    port: 9877,
    runnerPort: 9878,
    urlRoot: '/',
     /**
     * 'PhantomJS', 'Chrome', 'Opera', 'Safari', 'Firefox', 'ChromeCanary'
     */
    browsers: [
      'Chrome'//, 'Chrome', 'Opera', 'Safari', 'Firefox', 'ChromeCanary'
    ],
	 preprocessors: {
            // source files, that you wanna generate coverage for
            // do not include tests or libraries
            // (these files will be instrumented by Istanbul)

            'app/**/**/**/*service.js': ['coverage'],
			  'app/**/**/**/*factory.js': ['coverage'],
			
        },
	   // If browser does not capture in given timeout [ms], kill it
        captureTimeout: 60000,
	 // optionally, configure the reporter
        coverageReporter: {
            type: 'html',
            dir: 'grunt_assets/coverage/',

        },
		 // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,
		   // Continuous Integration mode
        // if true, it capture browsers, run tests and exit
        singleRun: false
  });
};

